import {
  Engineering, ElectricBolt, DirectionsCar, Warning, WaterDrop,
  Assessment, Description, Folder, CalendarToday,
  BarChart, AccountBalance,
  Power, ElectricalServices, SolarPower, Lightbulb, CreditCard,
  Map, Construction,
  CrisisAlert, NotificationsActive, School,
  Opacity, Settings, Recycling, Park,
} from '@mui/icons-material';

const UNITS_CONFIG = [
  {
    codigo: 'DI',
    nombre: 'Dirección de Infraestructura',
    color: '#1565c0',
    icono: Engineering,
    planEstrategico: 'Plan Estratégico de Infraestructura',
    items: [
      {
        key: 'planes-maestros',
        label: 'Planes Maestros',
        icon: Assessment,
        endpoint: '/gestion/plan-maestro',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'periodo', header: 'Periodo' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'periodo', label: 'Periodo', type: 'text' },
          { name: 'descripcion', label: 'Descripción', type: 'textarea' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['ELABORACION', 'APROBADO', 'EN_EJECUCION', 'COMPLETADO'] },
        ],
      },
      {
        key: 'diagnostico-necesidades',
        label: 'Diagnóstico Necesidades',
        icon: Description,
        endpoint: '/gestion/diagnosticos-necesidades',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'sector', header: 'Sector' },
          { field: 'municipio', header: 'Municipio' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'sector', label: 'Sector', type: 'text' },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'descripcion', label: 'Descripción', type: 'textarea' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['EN_ELABORACION', 'COMPLETADO', 'REVISION'] },
        ],
      },
      {
        key: 'portafolio-proyectos',
        label: 'Portafolio Proyectos',
        icon: Folder,
        endpoint: '/gestion/portafolio-proyectos',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo', type: 'chip' },
          { field: 'presupuestoEstimado', header: 'Presupuesto', type: 'money' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['FICHA_TECNICA', 'PRE_INVERSION', 'DISEÑO_FINAL'] },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'descripcion', label: 'Descripción', type: 'textarea' },
          { name: 'presupuestoEstimado', label: 'Presupuesto Estimado', type: 'number' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['EN_ELABORACION', 'REVISION', 'APROBADO', 'ARCHIVADO'] },
        ],
      },
      {
        key: 'pac',
        label: 'PAC',
        icon: CalendarToday,
        endpoint: '/gestion/pac',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'gestion', header: 'Gestión' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'gestion', label: 'Gestión', type: 'number' },
          { name: 'descripcion', label: 'Descripción', type: 'textarea' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['ELABORACION', 'APROBADO', 'EN_EJECUCION'] },
        ],
      },
      {
        key: 'programaciones-ejecucion',
        label: 'Programación Ejecución',
        icon: BarChart,
        endpoint: '/gestion/programaciones-ejecucion',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'gestion', header: 'Gestión' },
          { field: 'trimestre', header: 'Trimestre' },
          { field: 'avanceFisicoEjecutado', header: 'Avance Físico', type: 'progress' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'gestion', label: 'Gestión', type: 'number', required: true },
          { name: 'trimestre', label: 'Trimestre', type: 'select', options: [1, 2, 3, 4] },
          { name: 'avanceFisicoProgramado', label: 'Avance Físico Programado (%)', type: 'number' },
          { name: 'avanceFisicoEjecutado', label: 'Avance Físico Ejecutado (%)', type: 'number' },
          { name: 'presupuestoAsignado', label: 'Presupuesto Asignado', type: 'number' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['PROGRAMADO', 'EN_EJECUCION', 'COMPLETADO', 'OBSERVADO'] },
        ],
      },
      {
        key: 'presupuestos-base',
        label: 'Presupuesto Base',
        icon: AccountBalance,
        endpoint: '/gestion/presupuestos-base',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'gestion', header: 'Gestión' },
          { field: 'tipoPresupuesto', header: 'Tipo' },
          { field: 'montoTotal', header: 'Monto Total', type: 'money' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'gestion', label: 'Gestión', type: 'number', required: true },
          { name: 'tipoPresupuesto', label: 'Tipo', type: 'select', options: ['BASE', 'FLUJO_EFECTIVIDAD'] },
          { name: 'montoTotal', label: 'Monto Total', type: 'number' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['ELABORACION', 'APROBADO', 'EN_EJECUCION', 'CERRADO'] },
        ],
      },
    ],
  },
  {
    codigo: 'JE',
    nombre: 'Jefatura de Energía',
    color: '#2e7d32',
    icono: ElectricBolt,
    planEstrategico: 'Plan Estratégico de Energía y Electrificación',
    items: [
      {
        key: 'diagnostico-energetico',
        label: 'Diagnóstico Energético',
        icon: Power,
        endpoint: '/gestion/diagnosticos-energeticos',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'municipio', header: 'Municipio' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'descripcion', label: 'Descripción', type: 'textarea' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['EN_ELABORACION', 'COMPLETADO', 'REVISION'] },
        ],
      },
      {
        key: 'red-electrica',
        label: 'Red Eléctrica',
        icon: ElectricalServices,
        endpoint: '/gestion/red-electrica',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo' },
          { field: 'longitudKm', header: 'Longitud (km)' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['MEDIA_TENSION', 'BAJA_TENSION', 'TRANSFORMADOR'] },
          { name: 'longitudKm', label: 'Longitud (km)', type: 'number' },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['OPERATIVA', 'EN_CONSTRUCCION', 'OBSERVADA'] },
        ],
      },
      {
        key: 'proyectos-energia-renovable',
        label: 'Energías Renovables',
        icon: SolarPower,
        endpoint: '/gestion/proyectos-energia-renovable',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo' },
          { field: 'potenciaKw', header: 'Potencia (kW)' },
          { field: 'municipio', header: 'Municipio' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['SOLAR', 'EOLICA', 'BIOMASA', 'HIDROELECTRICA'] },
          { name: 'potenciaKw', label: 'Potencia (kW)', type: 'number' },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['PRE_INVERSION', 'DISEÑO', 'EJECUCION', 'OPERATIVO'] },
        ],
      },
      {
        key: 'eficiencias-energeticas',
        label: 'Eficiencia Energética',
        icon: Lightbulb,
        endpoint: '/gestion/eficiencias-energeticas',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'edificio', header: 'Edificio', flex: 2 },
          { field: 'tipoEdificio', header: 'Tipo' },
          { field: 'ahorroEstimadoPorcentaje', header: 'Ahorro (%)', type: 'progress' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'edificio', label: 'Edificio', type: 'text', required: true },
          { name: 'tipoEdificio', label: 'Tipo Edificio', type: 'select', options: ['OFICINA_GUBERNAMENTAL', 'ESCUELA', 'HOSPITAL', 'OTRO'] },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'consumoActualKwh', label: 'Consumo Actual (kWh)', type: 'number' },
          { name: 'consumoObjetivoKwh', label: 'Consumo Objetivo (kWh)', type: 'number' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['DIAGNOSTICO', 'PLANIFICACION', 'EN_EJECUCION', 'COMPLETADO'] },
        ],
      },
      {
        key: 'solicitudes-financiamiento',
        label: 'Solicitud Financiamiento',
        icon: CreditCard,
        endpoint: '/gestion/solicitudes-financiamiento',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'entidadFinanciera', header: 'Entidad' },
          { field: 'montoSolicitado', header: 'Monto', type: 'money' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'entidadFinanciera', label: 'Entidad', type: 'select', options: ['BID', 'CAF', 'Banco Mundial', 'Gobierno Central', 'Otro'] },
          { name: 'montoSolicitado', label: 'Monto Solicitado', type: 'number' },
          { name: 'tipoFinanciamiento', label: 'Tipo', type: 'select', options: ['PRESTAMO', 'DONACION', 'COFINANCIAMIENTO'] },
          { name: 'estado', label: 'Estado', type: 'select', options: ['EN_PREPARACION', 'ENVIADA', 'EN_EVALUACION', 'APROBADA', 'RECHAZADA'] },
        ],
      },
    ],
  },
  {
    codigo: 'JT',
    nombre: 'Jefatura de Transporte',
    color: '#e65100',
    icono: DirectionsCar,
    planEstrategico: 'Plan Estratégico de Transporte y Vialidad',
    items: [
      {
        key: 'planes-movilidad',
        label: 'Plan Movilidad',
        icon: Map,
        endpoint: '/gestion/planes-movilidad',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'ambito', header: 'Ámbito' },
          { field: 'municipio', header: 'Municipio' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'ambito', label: 'Ámbito', type: 'select', options: ['URBANO', 'RURAL', 'INTERURBANO'] },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'diagnostico', label: 'Diagnóstico', type: 'textarea' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['ELABORACION', 'APROBADO', 'EN_EJECUCION', 'COMPLETADO'] },
        ],
      },
      {
        key: 'red-vial',
        label: 'Red Vial',
        icon: Construction,
        endpoint: '/gestion/red-vial',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo' },
          { field: 'longitudKm', header: 'Longitud (km)' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['TRONCAL', 'SECUNDARIA', 'MUNICIPAL', 'VECINAL'] },
          { name: 'longitudKm', label: 'Longitud (km)', type: 'number' },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['BUENO', 'REGULAR', 'MALO', 'EN_CONSTRUCCION'] },
        ],
      },
      {
        key: 'mantenimiento-vial',
        label: 'Mantenimiento Vial',
        icon: Construction,
        endpoint: '/gestion/mantenimiento-vial',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo' },
          { field: 'fechaInicio', header: 'Inicio', type: 'date' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['PERIODICO', 'RUTINARIO', 'EMERGENCIA'] },
          { name: 'fechaInicio', label: 'Fecha Inicio', type: 'date' },
          { name: 'fechaFin', label: 'Fecha Fin', type: 'date' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['PROGRAMADO', 'EN_EJECUCION', 'COMPLETADO'] },
        ],
      },
      {
        key: 'licencias-vehiculo',
        label: 'Licencias Vehículo',
        icon: DirectionsCar,
        endpoint: '/gestion/licencias-vehiculo',
        columns: [
          { field: 'placa', header: 'Placa' },
          { field: 'tipoVehiculo', header: 'Tipo' },
          { field: 'propietario', header: 'Propietario', flex: 2 },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'placa', label: 'Placa', type: 'text', required: true },
          { name: 'tipoVehiculo', label: 'Tipo Vehículo', type: 'select', options: ['CAMION', 'BUS', 'PICKUP', 'MOTOCICLETA'] },
          { name: 'propietario', label: 'Propietario', type: 'text' },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['ACTIVA', 'VENCIDA', 'SUSPENDIDA'] },
        ],
      },
    ],
  },
  {
    codigo: 'JUPRE',
    nombre: 'JUPRE - Prevención Riesgos',
    color: '#6a1b9a',
    icono: Warning,
    planEstrategico: 'Plan de Prevención y Gestión de Riesgos',
    items: [
      {
        key: 'mapas-riesgo',
        label: 'Mapas de Riesgo',
        icon: Map,
        endpoint: '/gestion/mapas-riesgo',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo' },
          { field: 'nivelRiesgo', header: 'Nivel', type: 'chip' },
          { field: 'municipio', header: 'Municipio' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['INUNDACION', 'SISMO', 'DESLIZAMIENTO', 'SEQUÍA'] },
          { name: 'nivelRiesgo', label: 'Nivel Riesgo', type: 'select', options: ['BAJO', 'MEDIO', 'ALTO', 'CRITICO'] },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'descripcion', label: 'Descripción', type: 'textarea' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['EN_ELABORACION', 'APROBADO', 'ACTUALIZADO'] },
        ],
      },
      {
        key: 'planes-contingencia',
        label: 'Plan Contingencia',
        icon: CrisisAlert,
        endpoint: '/gestion/planes-contingencia',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipoEmergencia', header: 'Tipo' },
          { field: 'municipio', header: 'Municipio' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipoEmergencia', label: 'Tipo Emergencia', type: 'select', options: ['INUNDACION', 'SISMO', 'INCENDIO', 'DESLIZAMIENTO'] },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'descripcion', label: 'Descripción', type: 'textarea' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['ELABORACION', 'APROBADO', 'EN_ACTUALIZACION'] },
        ],
      },
      {
        key: 'sistemas-alerta',
        label: 'Sistemas Alerta',
        icon: NotificationsActive,
        endpoint: '/gestion/sistemas-alerta',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo' },
          { field: 'municipio', header: 'Municipio' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['HIDROLOGICO', 'SISMICO', 'METEOROLOGICO'] },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'descripcion', label: 'Descripción', type: 'textarea' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['INSTALADO', 'EN_INSTALACION', 'MANTENIMIENTO'] },
        ],
      },
      {
        key: 'capacitaciones-simulacros',
        label: 'Capacitación/Simulacros',
        icon: School,
        endpoint: '/gestion/capacitaciones-simulacros',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo' },
          { field: 'fechaProgramada', header: 'Fecha', type: 'date' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['CAPACITACION', 'SIMULACRO', 'TALLER'] },
          { name: 'tema', label: 'Tema', type: 'text' },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'fechaProgramada', label: 'Fecha Programada', type: 'date' },
          { name: 'participantesObjetivo', label: 'Participantes Objetivo', type: 'number' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['PROGRAMADO', 'EN_PREPARACION', 'REALIZADO', 'CANCELADO'] },
        ],
      },
    ],
  },
  {
    codigo: 'JUS',
    nombre: 'JUS - Saneamiento',
    color: '#c62828',
    icono: WaterDrop,
    planEstrategico: 'Plan de Saneamiento Básico y Gestión Ambiental',
    items: [
      {
        key: 'red-agua-potable',
        label: 'Red Agua Potable',
        icon: Opacity,
        endpoint: '/gestion/red-agua-potable',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo' },
          { field: 'longitudKm', header: 'Longitud (km)' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['CAPTACION', 'CONDUCCION', 'DISTRIBUCION'] },
          { name: 'longitudKm', label: 'Longitud (km)', type: 'number' },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['OPERATIVA', 'EN_CONSTRUCCION', 'OBSERVADA'] },
        ],
      },
      {
        key: 'plantas-tratamiento',
        label: 'Plantas Tratamiento',
        icon: Settings,
        endpoint: '/gestion/plantas-tratamiento',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo' },
          { field: 'capacidadM3', header: 'Capacidad (m³)' },
          { field: 'municipio', header: 'Municipio' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['PTAP', 'PTAR', 'LAGUNAS'] },
          { name: 'capacidadM3', label: 'Capacidad (m³/día)', type: 'number' },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['OPERATIVA', 'EN_CONSTRUCCION', 'MANTENIMIENTO'] },
        ],
      },
      {
        key: 'gestion-residuos',
        label: 'Gestión Residuos',
        icon: Recycling,
        endpoint: '/gestion/gestion-residuos',
        columns: [
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipo', header: 'Tipo' },
          { field: 'municipio', header: 'Municipio' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipo', label: 'Tipo', type: 'select', options: ['RELLENO_SANITARIO', 'PUNTO_LIMPIO', 'RECICLAJE'] },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'descripcion', label: 'Descripción', type: 'textarea' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['OPERATIVO', 'EN_CONSTRUCCION', 'PLANIFICACION'] },
        ],
      },
      {
        key: 'planes-cobertura-saneamiento',
        label: 'Plan Cobertura',
        icon: Park,
        endpoint: '/gestion/planes-cobertura-saneamiento',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipoSaneamiento', header: 'Tipo' },
          { field: 'coberturaActualPorcentaje', header: 'Cobertura (%)', type: 'progress' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipoSaneamiento', label: 'Tipo', type: 'select', options: ['AGUA_POTABLE', 'ALCANTARILLADO', 'AMBOS'] },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'coberturaActualPorcentaje', label: 'Cobertura Actual (%)', type: 'number' },
          { name: 'coberturaObjetivoPorcentaje', label: 'Cobertura Objetivo (%)', type: 'number' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['ELABORACION', 'APROBADO', 'EN_EJECUCION', 'COMPLETADO'] },
        ],
      },
      {
        key: 'gestiones-ambientales',
        label: 'Gestión Ambiental',
        icon: Park,
        endpoint: '/gestion/gestiones-ambientales',
        columns: [
          { field: 'codigo', header: 'Código' },
          { field: 'nombre', header: 'Nombre', flex: 2 },
          { field: 'tipoEvaluacion', header: 'Tipo' },
          { field: 'nivelImpacto', header: 'Impacto', type: 'chip' },
          { field: 'estado', header: 'Estado', type: 'chip' },
        ],
        formFields: [
          { name: 'codigo', label: 'Código', type: 'text', required: true },
          { name: 'nombre', label: 'Nombre', type: 'text', required: true },
          { name: 'tipoEvaluacion', label: 'Tipo Evaluación', type: 'select', options: ['EIA', 'AUDITORIA', 'MONITOREO', 'PLAN_MANEJO'] },
          { name: 'componente', label: 'Componente', type: 'select', options: ['AGUA', 'SUELO', 'AIRE', 'FLORA', 'FAUNA', 'SOCIOECONOMICO'] },
          { name: 'nivelImpacto', label: 'Nivel Impacto', type: 'select', options: ['BAJO', 'MEDIO', 'ALTO', 'CRITICO'] },
          { name: 'municipio', label: 'Municipio', type: 'text' },
          { name: 'estado', label: 'Estado', type: 'select', options: ['EN_EVALUACION', 'APROBADO', 'EN_EJECUCION', 'CUMPLIDO', 'OBSERVADO'] },
        ],
      },
    ],
  },
];

export default UNITS_CONFIG;
